# 1. Transforming data - Scaling

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/sharmaroshan/Social-Networks-Ads/master/Social_Network_Ads.csv")

In [7]:
df.to_csv("social_net_ads.csv",index = False)

In [8]:
df.head()

    User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [9]:
df = df.iloc[:,2:]

In [10]:
df

      Age  EstimatedSalary  Purchased
0    19.0          19000.0          0
1    35.0          20000.0          0
2    26.0          43000.0          0
3    27.0          57000.0          0
4    19.0          76000.0          0
..    ...              ...        ...
395  46.0          41000.0          1
396  51.0          23000.0          1
397  50.0          20000.0          1
398  36.0          33000.0          0
399  49.0          36000.0          1

[400 rows x 3 columns]

# Train test split

In [12]:
#training data -70 -80 % for prediction ,,,,,testing data -20%======to check the accuracy

In [13]:
#first we have to install scikit-learn

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
df

      Age  EstimatedSalary  Purchased
0    19.0          19000.0          0
1    35.0          20000.0          0
2    26.0          43000.0          0
3    27.0          57000.0          0
4    19.0          76000.0          0
..    ...              ...        ...
395  46.0          41000.0          1
396  51.0          23000.0          1
397  50.0          20000.0          1
398  36.0          33000.0          0
399  49.0          36000.0          1

[400 rows x 3 columns]

In [16]:
#dropped purchase because of no use in feature engineering
df.drop("Purchased",axis = 1)

      Age  EstimatedSalary
0    19.0          19000.0
1    35.0          20000.0
2    26.0          43000.0
3    27.0          57000.0
4    19.0          76000.0
..    ...              ...
395  46.0          41000.0
396  51.0          23000.0
397  50.0          20000.0
398  36.0          33000.0
399  49.0          36000.0

[400 rows x 2 columns]

In [17]:
df.shape

(400, 3)

In [19]:
x_train,x_test,y_train,y_test = train_test_split(df.drop("Purchased",axis=1),df["Purchased"],test_size = 0.25)

In [21]:
x_train

      Age  EstimatedSalary
230  35.0         147000.0
145  24.0          89000.0
93   29.0          28000.0
393  60.0          42000.0
122  40.0          75000.0
..    ...              ...
95   35.0          44000.0
69   31.0          68000.0
387  39.0          71000.0
41   33.0          51000.0
236  40.0          57000.0

[300 rows x 2 columns]

In [40]:
x_test

      Age  EstimatedSalary
33   28.0          44000.0
45   23.0          20000.0
78   28.0          87000.0
368  38.0          71000.0
311  39.0          96000.0
..    ...              ...
379  58.0          23000.0
65   24.0          58000.0
323  48.0          30000.0
178  24.0          23000.0
266  40.0          75000.0

[100 rows x 2 columns]

In [41]:
y_train

230    1
145    0
93     0
393    1
122    0
      ..
95     0
69     0
387    0
41     0
236    0
Name: Purchased, Length: 300, dtype: int64

In [42]:
y_test

33     0
45     0
78     0
368    0
311    1
      ..
379    1
65     0
323    1
178    0
266    0
Name: Purchased, Length: 100, dtype: int64

In [23]:
x_train.shape

(300, 2)

In [27]:
x_test.shape

(100, 2)

In [28]:
y_train.shape

(300,)

In [25]:
y_test.shape

(100,)

# Standard Scaler

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
scaler = StandardScaler()

In [33]:
scaler.fit(x_train)

StandardScaler()

In [35]:
x_train_scaled  =scaler.fit_transform(x_train)
x_train_scaled

array([[-0.23881112,  2.27062365],
       [-1.28958005,  0.5685363 ],
       [-0.81195781, -1.22159005],
       [ 2.14930008, -0.81074138],
       [ 0.23881112,  0.15768763],
       [-0.71643336,  1.09677031],
       [-1.3851045 , -1.22159005],
       [ 0.71643336,  1.80108231],
       [ 0.90748226, -0.60531704],
       [ 1.95825118, -0.92812671],
       [ 0.14328667,  1.06742397],
       [ 1.57615339,  1.12611664],
       [ 0.52538446,  1.74238965],
       [-1.0030067 , -0.34120004],
       [-1.0030067 , -0.34120004],
       [-0.33433557, -0.78139504],
       [-0.23881112, -1.36832172],
       [ 2.05377563,  0.3924583 ],
       [ 1.48062894, -1.04551205],
       [-1.09853115, -1.60309238],
       [ 0.04776222,  1.27284831],
       [ 0.23881112,  0.24572663],
       [ 0.71643336, -1.39766805],
       [ 0.04776222, -0.42923904],
       [-0.23881112, -0.37054637],
       [ 1.3851045 , -1.42701438],
       [-0.90748226, -1.10420471],
       [ 1.09853115,  0.4804973 ],
       [ 1.67167784, -0.89878038],
       [ 1.09853115, -0.89878038],
       [ 1.67167784,  1.77173598],
       [ 0.14328667,  1.88912132],
       [-1.67167784,  0.1283413 ],
       [ 0.04776222,  0.0403023 ],
       [ 1.28958005,  2.24127732],
       [ 0.14328667,  0.09899497],
       [-0.52538446,  1.39023364],
       [-0.23881112,  1.12611664],
       [-1.0030067 ,  0.53918997],
       [ 0.90748226, -0.54662437],
       [ 0.90748226, -0.78139504],
       [ 0.42986002, -0.16512204],
       [ 2.05377563,  1.77173598],
       [-0.42986002, -0.28250737],
       [ 1.09853115,  0.5685363 ],
       [ 0.04776222, -0.57597071],
       [-0.14328667,  2.18258465],
       [ 0.33433557, -0.28250737],
       [-1.57615339, -1.57374605],
       [-1.09853115, -1.57374605],
       [-1.1940556 ,  0.59788264],
       [-1.76720229, -1.42701438],
       [-1.86272674, -0.75204871],
       [-0.71643336,  0.50984364],
       [-0.52538446,  0.4804973 ],
       [ 1.48062894,  0.36311197],
       [-1.1940556 ,  0.27507297],
       [-1.86272674,  0.36311197],
       [ 0.04776222, -0.25316104],
       [-1.09853115,  1.41957998],
       [-0.52538446,  0.89134597],
       [-0.52538446,  1.91846765],
       [ 2.05377563,  2.15323832],
       [-1.0030067 ,  1.97716032],
       [ 1.57615339,  0.01095596],
       [ 0.14328667, -0.31185371],
       [-0.42986002, -0.84008771],
       [-0.23881112,  0.53918997],
       [ 1.09853115, -0.1357757 ],
       [ 1.0030067 , -1.19224371],
       [ 1.09853115,  2.09454565],
       [-0.90748226,  0.5685363 ],
       [ 0.90748226,  1.09677031],
       [ 0.33433557,  0.27507297],
       [-1.09853115,  0.4804973 ],
       [-1.09853115, -1.16289738],
       [-1.1940556 , -1.07485838],
       [-0.81195781, -0.66400971],
       [-0.33433557, -0.78139504],
       [ 1.3851045 ,  1.30219464],
       [-0.42986002,  1.27284831],
       [-0.42986002,  2.32931632],
       [ 0.90748226,  1.03807764],
       [-0.04776222,  0.1283413 ],
       [-0.62090891, -0.34120004],
       [ 0.42986002,  1.12611664],
       [-1.09853115,  0.33376563],
       [-0.71643336, -1.54439972],
       [-0.71643336, -1.60309238],
       [-1.1940556 ,  0.50984364],
       [ 1.67167784,  1.62500431],
       [ 0.42986002,  0.09899497],
       [-0.23881112, -1.25093638],
       [-0.04776222,  0.15768763],
       [ 0.33433557,  0.50984364],
       [-0.33433557, -1.30962905],
       [-0.81195781, -0.78139504],
       [ 0.52538446,  1.85977498],
       [-0.33433557,  0.06964863],
       [ 0.71643336, -1.10420471],
       [ 2.14930008,  0.95003864],
       [ 0.23881112, -0.37054637],
       [-0.23881112, -0.66400971],
       [ 0.23881112,  2.12389198],
       [-1.76720229, -1.30962905],
       [ 1.0030067 ,  0.1283413 ],
       [-0.04776222,  0.24572663],
       [-1.28958005, -1.10420471],
       [ 0.14328667,  1.88912132],
       [-0.42986002, -1.22159005],
       [-0.23881112,  0.06964863],
       [ 1.48062894,  0.06964863],
       [-1.67167784,  0.36311197],
       [-1.28958005, -1.48570705],
       [-1.0030067 ,  0.77396064],
       [ 0.42986002,  0.3044193 ],
       [ 0.71643336, -1.28028271],
       [-0.62090891,  1.41957998],
       [ 1.09853115, -0.98681938],
       [ 0.04776222, -0.57597071],
       [ 0.81195781, -1.22159005],
       [ 0.33433557,  0.06964863],
       [ 1.0030067 ,  2.00650665],
       [-0.62090891,  0.5685363 ],
       [-0.23881112, -0.28250737],
       [-1.09853115,  0.42180464],
       [-1.28958005,  0.42180464],
       [-0.33433557,  1.33154098],
       [ 1.09853115,  0.1283413 ],
       [ 0.23881112, -0.66400971],
       [-1.86272674, -0.51727804],
       [ 2.14930008,  0.3924583 ],
       [-0.14328667, -0.28250737],
       [-0.14328667,  1.62500431],
       [ 1.0030067 ,  1.44892631],
       [ 0.90748226, -1.45636072],
       [-0.81195781,  0.3924583 ],
       [-0.04776222, -0.48793171],
       [-0.04776222, -0.37054637],
       [ 0.81195781,  0.36311197],
       [ 1.09853115, -1.22159005],
       [-1.86272674, -0.0477367 ],
       [ 0.42986002,  0.59788264],
       [-0.81195781,  0.15768763],
       [-0.04776222,  2.24127732],
       [-0.81195781,  0.3044193 ],
       [-1.09853115,  0.3044193 ],
       [-0.14328667, -0.45858537],
       [-0.04776222,  0.27507297],
       [-1.76720229, -1.48570705],
       [-0.04776222,  1.97716032],
       [-1.48062894,  0.33376563],
       [-0.23881112,  0.80330697],
       [ 0.33433557, -0.51727804],
       [ 0.23881112, -0.28250737],
       [-0.14328667, -0.19446837],
       [-1.09853115, -1.60309238],
       [-0.90748226, -0.95747304],
       [ 1.1940556 , -1.45636072],
       [-1.48062894, -0.19446837],
       [ 0.71643336, -1.39766805],
       [-1.0030067 , -0.45858537],
       [-0.90748226,  0.42180464],
       [-0.04776222,  0.2163803 ],
       [-0.62090891, -1.60309238],
       [ 1.0030067 , -0.84008771],
       [ 1.09853115,  0.53918997],
       [ 1.1940556 , -0.98681938],
       [ 0.23881112, -0.1357757 ],
       [ 0.81195781,  0.53918997],
       [ 1.86272674, -1.07485838],
       [-0.42986002, -0.01839037],
       [-0.62090891,  0.0403023 ],
       [-0.81195781,  0.3924583 ],
       [-0.81195781, -0.78139504],
       [-0.90748226, -0.31185371],
       [-0.23881112, -1.45636072],
       [ 0.42986002, -0.48793171],
       [-0.90748226, -0.31185371],
       [-0.23881112,  0.15768763],
       [-1.0030067 , -1.54439972],
       [-0.23881112, -0.1357757 ],
       [-0.62090891,  0.1283413 ],
       [ 1.09853115, -1.22159005],
       [ 0.90748226, -1.36832172],
       [-1.57615339,  0.53918997],
       [-0.04776222, -0.42923904],
       [ 1.1940556 , -0.75204871],
       [-0.23881112,  0.0403023 ],
       [ 1.57615339,  1.00873131],
       [ 0.33433557, -0.19446837],
       [ 1.0030067 ,  0.59788264],
       [ 0.42986002,  0.3044193 ],
       [-1.67167784, -0.60531704],
       [ 0.81195781,  0.27507297],
       [ 1.86272674,  0.1283413 ],
       [ 0.23881112,  0.0403023 ],
       [ 0.71643336, -0.72270238],
       [-1.09853115, -0.78139504],
       [ 0.23881112,  1.09677031],
       [ 0.23881112, -0.37054637],
       [-0.42986002, -1.13355105],
       [-0.33433557,  1.24350198],
       [-1.1940556 , -1.39766805],
       [-0.90748226,  0.45115097],
       [-0.23881112,  0.15768763],
       [ 0.81195781, -1.39766805],
       [ 2.14930008, -0.81074138],
       [-1.0030067 ,  0.42180464],
       [ 1.95825118,  2.18258465],
       [-0.23881112,  0.27507297],
       [-0.23881112, -0.34120004],
       [ 2.14930008, -1.04551205],
       [ 0.04776222,  1.24350198],
       [-0.14328667, -0.51727804],
       [ 1.48062894,  1.00873131],
       [ 2.05377563, -0.81074138],
       [ 0.14328667,  0.2163803 ],
       [ 0.14328667,  0.15768763],
       [-0.71643336,  1.36088731],
       [ 1.76720229,  1.85977498],
       [ 0.81195781, -0.84008771],
       [-0.52538446, -1.51505338],
       [-0.81195781,  2.29996999],
       [ 0.42986002, -0.1357757 ],
       [ 0.33433557, -0.54662437],
       [-0.90748226, -0.42923904],
       [-0.04776222,  0.0403023 ],
       [ 0.23881112, -0.25316104],
       [ 1.0030067 ,  0.77396064],
       [ 1.95825118,  0.7446143 ],
       [-0.14328667, -0.57597071],
       [ 0.81195781, -0.31185371],
       [-0.04776222,  0.06964863],
       [ 0.90748226,  1.27284831],
       [ 0.14328667, -0.81074138],
       [-1.28958005, -1.25093638],
       [-1.86272674,  0.4804973 ],
       [ 0.04776222, -0.1357757 ],
       [-1.09853115, -1.10420471],
       [-1.0030067 , -0.37054637],
       [-0.71643336,  1.91846765],
       [ 0.33433557, -0.31185371],
       [-0.04776222,  0.3044193 ],
       [ 1.0030067 , -1.07485838],
       [-0.71643336,  0.5685363 ],
       [ 0.33433557,  0.06964863],
       [-0.23881112,  0.09899497],
       [-0.04776222,  0.68592164],
       [ 1.0030067 , -1.01616571],
       [ 0.90748226, -1.30962905],
       [ 2.05377563, -1.19224371],
       [-1.76720229,  0.18703397],
       [-1.48062894, -1.25093638],
       [-0.23881112, -0.42923904],
       [-1.3851045 , -0.19446837],
       [-1.28958005, -0.42923904],
       [ 2.05377563,  0.18703397],
       [ 0.14328667, -0.81074138],
       [-0.04776222,  0.01095596],
       [ 2.14930008, -0.69335604],
       [-1.0030067 ,  0.59788264],
       [ 0.42986002, -0.45858537],
       [-0.14328667, -1.07485838],
       [ 0.33433557, -1.16289738],
       [ 1.0030067 , -1.07485838],
       [ 1.86272674,  1.53696531],
       [-1.3851045 , -0.63466337],
       [-1.09853115, -1.01616571],
       [-1.3851045 , -0.10642937],
       [-1.3851045 ,  0.36311197],
       [-0.04776222, -1.07485838],
       [-0.71643336, -0.60531704],
       [ 1.0030067 ,  1.80108231],
       [ 1.28958005, -1.36832172],
       [-1.76720229,  0.45115097],
       [-0.04776222,  2.18258465],
       [-0.23881112, -0.89878038],
       [-1.1940556 ,  0.3044193 ],
       [ 0.42986002,  2.32931632],
       [ 1.48062894,  2.15323832],
       [ 0.04776222, -0.31185371],
       [-0.23881112, -1.30962905],
       [ 0.42986002,  0.01095596],
       [ 1.3851045 , -0.92812671],
       [-0.23881112, -0.31185371],
       [ 0.42986002,  0.15768763],
       [ 0.62090891, -0.89878038],
       [ 0.62090891,  2.03585298],
       [-1.09853115,  0.06964863],
       [-1.57615339,  0.06964863],
       [ 0.04776222,  0.3044193 ],
       [-1.76720229, -1.28028271],
       [-0.14328667,  0.15768763],
       [-1.09853115,  0.3044193 ],
       [-0.23881112, -0.75204871],
       [-0.62090891, -0.0477367 ],
       [ 0.14328667,  0.0403023 ],
       [-0.42986002, -0.54662437],
       [ 0.23881112, -0.37054637]])

In [36]:
x_test_scaled = scaler.fit_transform(x_test)

In [38]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns=x_train.columns)
x_train_scaled

          Age  EstimatedSalary
0   -0.238811         2.270624
1   -1.289580         0.568536
2   -0.811958        -1.221590
3    2.149300        -0.810741
4    0.238811         0.157688
..        ...              ...
295 -0.238811        -0.752049
296 -0.620909        -0.047737
297  0.143287         0.040302
298 -0.429860        -0.546624
299  0.238811        -0.370546

[300 rows x 2 columns]